version: '3.8'

services:
  spotifytrackbot:
    build:
      dockerfile: Dockerfile
    restart: always
    ports:
      - "80:80"
    network_mode: host

networks:
  default:
    external: true
    name: my-net
