services:
  spotifytrackbot:
    build:
      dockerfile: Dockerfile
    restart: always
    ports:
      - "80:80"
    network_mode: host
    volumes:
      - ./docker-data/logs:/usr/src/app/logs

networks:
  default:
    external: true
    name: my-net